fix: translation strings (DHIS2-10630)
dhis2/app-management-app pull request #199
Opened 2021-03-17 17:13 UTC by KaiVandivier

Relates to https://jira.dhis2.org/browse/DHIS2-10630 and https://jira.dhis2.org/browse/DHIS2-10664, I believe

Adds translation strings for page headers and 'no apps installed' messages

Controversial: adds legacy i18n to translate '** search **' in the search bar from d2-ui Sidebar (see the second commit). If this one string isn't worth the legacy i18n, I can remove it :)

2021-03-22 14:58 UTC, HendrikThePendric requested changes
Since this app is still relying on, and has a working implementation of, the legacy i18n system, I think we should make sure these strings are fixed too. So I don't think anything needs to be removed from this PR.

I do think that we may have missed a few strings, for example this seems to result in hardcoded strings:

https://github.com/dhis2/app-management-app/blob/67bd72c075fad3ffd33bf7e712ed60686455cdc3/src/actions.js#L11-L24

I know it is possible to apply i18n to these `Actions`. At first glance it seems you could wrap the action name in `i18n.t()`, like so:
```js
 installApp: Action.create(i18n.t('Install App')),
 ```
 
 If this is not providing the expected results, I think you could check either the user-app or the maintenance app to see how they've implemented things.

And quite likely this is ending up as hardcoded text in the UI too:
https://github.com/dhis2/app-management-app/blob/67bd72c075fad3ffd33bf7e712ed60686455cdc3/src/components/SelfUpdateNoticeBox.component.js#L11

I'm not sure we want to translate the app-name, but if we do, this needs to be wrapped in a call to `i18n.t()`

2021-03-22 15:11 UTC, KaiVandivier commented
Ah thanks @HendrikThePendric, I wasn't aware of those :) I'll fix those up too

2021-03-22 15:33 UTC, KaiVandivier commented
Added translations for those actions.

It looks like 'appManagementAppName' is used to find the app on the app hub, and is never displayed, so it doesn't need a translation 👍 

https://github.com/dhis2/app-management-app/blob/67bd72c075fad3ffd33bf7e712ed60686455cdc3/src/components/SelfUpdateNoticeBox.component.js#L37-L41

2021-03-29 09:24 UTC, HendrikThePendric approved these changes

2021-04-01 10:24 UTC, merged